tap "oven-sh/bun"
brew "chezmoi"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "imagemagick"
brew "lazygit"
brew "luarocks"
brew "mas"
brew "neovim"
brew "nvm"
brew "pandoc"
brew "ripgrep"
brew "rustup"
brew "starship"
brew "tectonic"
brew "yazi"
brew "zoxide"
brew "oven-sh/bun/bun"
cask "blip"
cask "font-hack-nerd-font"
cask "font-monaspace"
cask "google-chrome"
cask "keka"
cask "kitty"
cask "mos"
cask "visual-studio-code"
mas "AdBlocker", id: 1018301773
mas "APTV", id: 1630403500
mas "Command X", id: 6448461551
mas "Developer", id: 640199958
mas "Goodnotes", id: 1444383602
mas "Infuse", id: 1136220934
mas "Keynote讲演", id: 409183694
mas "Numbers表格", id: 409203825
mas "Pages文稿", id: 409201541
mas "Quantumult X", id: 1443988620
mas "WhatsApp", id: 310633997
mas "克拉壁纸", id: 1469525516
vscode "1yib.rust-bundle"
vscode "aaron-bond.better-comments"
vscode "alefragnani.project-manager"
vscode "astro-build.astro-vscode"
vscode "azemoh.one-monokai"
vscode "biomejs.biome"
vscode "christian-kohler.npm-intellisense"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "digitalbrainstem.javascript-ejs-support"
vscode "donjayamanne.githistory"
vscode "dustypomerleau.rust-syntax"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "fill-labs.dependi"
vscode "formulahendry.code-runner"
vscode "franneck94.c-cpp-runner"
vscode "github.codespaces"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.remotehub"
vscode "github.vscode-pull-request-github"
vscode "kevinrose.vsc-python-indent"
vscode "kisstkondoros.vscode-gutter-preview"
vscode "llvm-vs-code-extensions.lldb-dap"
vscode "mechatroner.rainbow-csv"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-zh-hans"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.live-server"
vscode "ms-vscode.powershell"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "ritwickdey.liveserver"
vscode "rust-lang.rust-analyzer"
vscode "slint.slint"
vscode "streetsidesoftware.code-spell-checker"
vscode "sumneko.lua"
vscode "swiftlang.swift-vscode"
vscode "twxs.cmake"
vscode "vadimcn.vscode-lldb"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vue.volar"
vscode "w88975.code-translate"
vscode "wallabyjs.quokka-vscode"
vscode "xabikos.javascriptsnippets"
vscode "zhuangtongfa.material-theme"
